### ISSUE TITLE
Can't pip install unless flask is already installed

### ISSUE THREAD

**Issue by sujaymansingh** [fraoustin/flask-monitor#2]

**Comment by sujaymansingh** [comment]
```
$ /tmp/test-install-flask-monitor/bin/pip install flask-monitor
Collecting flask-monitor
  Downloading flask-monitor-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7t/mvtvspqx3xz0w2qdgb64g9jc0000gn/T/pip-build-_vaodimg/flask-monitor/setup.py", line 10, in <module>
        import flask_monitor as mypkg
      File "/private/var/folders/7t/mvtvspqx3xz0w2qdgb64g9jc0000gn/T/pip-build-_vaodimg/flask-monitor/flask_monitor/__init__.py", line 16, in <module>
        from flask_monitor.main import *
      File "/private/var/folders/7t/mvtvspqx3xz0w2qdgb64g9jc0000gn/T/pip-build-_vaodimg/flask-monitor/flask_monitor/main.py", line 5, in <module>
        from flask import current_app, request, Blueprint
    ModuleNotFoundError: No module named 'flask'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7t/mvtvspqx3xz0w2qdgb64g9jc0000gn/T/pip-build-_vaodimg/flask-monitor/

$ /tmp/test-install-flask-monitor/bin/pip install flask
Collecting flask
  Using cached Flask-0.12.2-py2.py3-none-any.whl
Collecting click>=2.0 (from flask)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from flask)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from flask)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask)
  Using cached itsdangerous-0.24.tar.gz
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->flask)
  Using cached MarkupSafe-1.0.tar.gz
Installing collected packages: click, MarkupSafe, Jinja2, Werkzeug, itsdangerous, flask
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for itsdangerous ... done
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 Werkzeug-0.12.2 click-6.7 flask-0.12.2 itsdangerous-0.24

$ /tmp/test-install-flask-monitor/bin/pip install flask-monitor
Collecting flask-monitor
  Using cached flask-monitor-0.2.2.tar.gz
Requirement already satisfied: flask in /private/tmp/test-install-flask-monitor/lib/python3.6/site-packages (from flask-monitor)
Requirement already satisfied: six in /private/tmp/test-install-flask-monitor/lib/python3.6/site-packages (from flask-monitor)
Requirement already satisfied: Werkzeug>=0.7 in /private/tmp/test-install-flask-monitor/lib/python3.6/site-packages (from flask->flask-monitor)
Requirement already satisfied: Jinja2>=2.4 in /private/tmp/test-install-flask-monitor/lib/python3.6/site-packages (from flask->flask-monitor)
Requirement already satisfied: itsdangerous>=0.21 in /private/tmp/test-install-flask-monitor/lib/python3.6/site-packages (from flask->flask-monitor)
Requirement already satisfied: click>=2.0 in /private/tmp/test-install-flask-monitor/lib/python3.6/site-packages (from flask->flask-monitor)
Requirement already satisfied: MarkupSafe>=0.23 in /private/tmp/test-install-flask-monitor/lib/python3.6/site-packages (from Jinja2>=2.4->flask->flask-monitor)
Installing collected packages: flask-monitor
  Running setup.py install for flask-monitor ... done
Successfully installed flask-monitor-0.2.2
```

**Comment by sujaymansingh** [comment]
This is because the `setup.py` import `flask_monitor` for the meta-info about version etc.
https://github.com/fraoustin/flask-monitor/blob/0.2.2/setup.py#L10

But that itself imports `flask`, so the `setup.py` can't run unless `flask` is already installed.

@fraoustin How would you feel about moving the meta `__namepkg__` etc variables somewhere else? Perhaps into a text file or even `meta.py` file?

**Comment by sujaymansingh** [comment]
Or perhaps directly into `setup.py`? Those `__*__` variables are only used by `setup.py` from what I can see.

**Comment by fraoustin** [comment]
Hi ... REQUIREMENTS.txt contains flask so when you run "pip install" pip shoud install flask

**Comment by fraoustin** [comment]
thank you for pull requests

**Comment by sujaymansingh** [comment]
No problem at all @fraoustin. Thanks for merging! 👍
